### ISSUE TITLE
As an administrator, I can read from an input file so that new campuses and their souvenirs can be added.

### ISSUE THREAD

**Issue by gomihiko** [gomihiko/CollegeTouringS21#13]
1.	Description:
a.	The program will have an option to add new campuses and their souvenirs. The option will only be available to an administrator user. When adding new campuses, the information is read from an external input file.
2.	Tasks:
a.	As an administrator, I should be able to add new campuses and their souvenirs at any time.
b.	As an administrator, I should be able to provide an input file to be read by the program.
3.	Tests:
a.	Verify that the option to add campuses is only available to an administrator.
b.	Verify that an external file can be read by the program.
c.	Verify that the correct information is being stored when reading from the external file.
d.	Verify that the program does not attempt to add more campuses that can be stored at the time.
4.	Assignee:
a.	Yaseen Khan
5.	Estimation: 10
6.	Assumptions:
a.	The input file will follow a predefined format for all values that are intended to be read.
b.	There is appropriate memory space for new campuses to be stored.
7.	Priority:
a.	S1
8.	Done:
a.	Administrator can access the option to add campuses and their souvenirs.
b.	Program reads from an external file to obtain information about campuses and souvenirs.
c.	Information read from an external file is stored in the correct data structures.

**Comment by gomihiko** [comment]
I started this to complete the user story I was working on, the DbManager class should come in handy for this.

**Comment by Ykhan799** [comment]
![Uploading Screen Shot 2021-03-14 at 7.25.10 PM.png…]()
